Set MACOSX_SDK_VERSION to 10.12 due to TARGET_OS_OSX not set
Error:

cargo:warning=upstream/src/sljit/sljitExecAllocator.c:105:5: error: 'TARGET_OS_OSX' is not defined, evaluates to 0 [-Werror,-Wundef-prefix=TARGET_OS_OSX]